"""add workspace lifecycle status

Revision ID: 0b7fc4eea262
Revises: f57c90fdb4a9
Create Date: 2026-06-21 15:36:05.106099
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0b7fc4eea262"
down_revision: str | Sequence[str] | None = "f57c90fdb4a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workspaces",
        sa.Column(
            "status",
            sa.String(length=40),
            server_default="active",
            nullable=False,
        ),
    )
    op.add_column(
        "workspaces",
        sa.Column("deletion_requested_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "workspaces",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspaces", "deleted_at")
    op.drop_column("workspaces", "deletion_requested_at")
    op.drop_column("workspaces", "status")
    # ### end Alembic commands ###
