"""add user password hash

Revision ID: 29565468fb2e
Revises: b78aafeb9b49
Create Date: 2026-06-21 10:43:00.609473
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "29565468fb2e"
down_revision: str | Sequence[str] | None = "b78aafeb9b49"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password_hash", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_hash")
    # ### end Alembic commands ###
