"""add usage events

Revision ID: 7f10bb006ed3
Revises: 29565468fb2e
Create Date: 2026-06-21 12:25:37.847370
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7f10bb006ed3"
down_revision: str | Sequence[str] | None = "29565468fb2e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usage_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("actor_user_id", sa.String(length=36), nullable=True),
        sa.Column("metric_name", sa.String(length=80), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit", sa.String(length=40), nullable=False),
        sa.Column("source_type", sa.String(length=80), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=True),
        sa.Column("usage_metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_usage_events_workspace_created",
        "usage_events",
        ["workspace_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_usage_events_workspace_metric",
        "usage_events",
        ["workspace_id", "metric_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_usage_events_workspace_metric", table_name="usage_events")
    op.drop_index("ix_usage_events_workspace_created", table_name="usage_events")
    op.drop_table("usage_events")
    # ### end Alembic commands ###
