"""add workspace subscriptions

Revision ID: ccad477a19bb
Revises: 7f10bb006ed3
Create Date: 2026-06-21 13:40:21.406711
"""

from collections.abc import Sequence
from datetime import UTC, datetime
from uuid import uuid4

import sqlalchemy as sa
from alembic import op

revision: str = "ccad477a19bb"
down_revision: str | Sequence[str] | None = "7f10bb006ed3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspace_subscriptions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("plan_name", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id"),
    )
    op.create_index(
        "ix_workspace_subscriptions_workspace",
        "workspace_subscriptions",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    _backfill_free_subscriptions()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_workspace_subscriptions_workspace", table_name="workspace_subscriptions")
    op.drop_table("workspace_subscriptions")
    # ### end Alembic commands ###


def _backfill_free_subscriptions() -> None:
    connection = op.get_bind()
    workspace_ids = list(connection.scalars(sa.text("SELECT id FROM workspaces")).all())

    if not workspace_ids:
        return

    now = datetime.now(UTC)
    subscription_table = sa.table(
        "workspace_subscriptions",
        sa.column("id", sa.String),
        sa.column("workspace_id", sa.String),
        sa.column("plan_name", sa.String),
        sa.column("status", sa.String),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )

    op.bulk_insert(
        subscription_table,
        [
            {
                "id": str(uuid4()),
                "workspace_id": workspace_id,
                "plan_name": "free",
                "status": "active",
                "created_at": now,
                "updated_at": now,
            }
            for workspace_id in workspace_ids
        ],
    )
