"""add platform admin flag

Revision ID: f57c90fdb4a9
Revises: ccad477a19bb
Create Date: 2026-06-21 13:58:58.747882
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f57c90fdb4a9"
down_revision: str | Sequence[str] | None = "ccad477a19bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_platform_admin",
            sa.Boolean(),
            server_default=sa.false(),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_platform_admin")
    # ### end Alembic commands ###
